### ISSUE TITLE
Errors with express 4.x in oauth2 example

### ISSUE THREAD

**Issue by chmorgan** [jaredhanson/passport-google-oauth#37]
oauth2]$ node app.js 

/home/cmorgan/bitsplash/noteapp/passport-google-oauth/examples/oauth2/app.js:53
var app = express.createServer();
                  ^
TypeError: Object function createApplication() {
  var app = function(req, res, next) {
    app.handle(req, res, next);
  };

  mixin(app, proto);
  mixin(app, EventEmitter.prototype);

  app.request = { __proto__: req, app: app };
  app.response = { __proto__: res, app: app };
  app.init();
  return app;
} has no method 'createServer'
    at Object.<anonymous> (/home/cmorgan/bitsplash/noteapp/passport-google-oauth/examples/oauth2/app.js:53:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by Waowam** [comment]
It's been a while but we could close this one.

Passport-google-oauth's examples are based on express 3.x.
Using them with express 4.x will raised this error.

I guess, we might update examples.
