### ISSUE TITLE
Failed to fetch user profile

### ISSUE THREAD

**Issue by shoemaker** [jaredhanson/passport-google-oauth#46]
The passport-google-oauth module began failing earlier this month. The actual authentication seems to work, but the follow-up request for the user's profile fails with the following error: 

failed to fetch user profile (status: 401 data:

```
{
  "error": {
    "errors": [
      {
        "domain": "global",
        "reason": "authError",
        "message": "Invalid Credentials",
        "locationType": "header",
        "location": "Authorization"
      }
    ],
    "code": 401,
    "message": "Invalid Credentials"
  }
}
```

 )

I have recreated a new OAuth key/secret via the Google developer console, no change in the outcome.

**Comment by letunglam** [comment]
@shoemaker How can you fixed this?

I have same error. Bellow is my error stack:

```
InternalOAuthError: failed to fetch user profile
    at /app/node_modules/passport-google-oauth2/lib/oauth2.js:92:28
    at passBackControl (/app/node_modules/passport-google-oauth2/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:124:9)
    at IncomingMessage.<anonymous> (/app/node_modules/passport-google-oauth2/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

Any help would be appreciated

**Comment by qrpike** [comment]
+1 Im getting the same error

**Comment by basickarl** [comment]
+1 Same:
```  InternalOAuthError: failed to fetch user profile
      at /home/karl/www/app/node_modules/passport-google-oauth/lib/passport-google-oauth/oauth2.js:88:28
      at passBackControl (/home/karl/www/app/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:124:9)
      at IncomingMessage.<anonymous> (/home/karl/www/app/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
      at IncomingMessage.emit (events.js:129:20)
      at _stream_readable.js:908:16
      at process._tickCallback (node.js:355:11)
```

**Comment by basickarl** [comment]
```{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}```

If you get this, go into https://console.developers.google.com into your project api, you must enable Google+ API.

**Comment by peterbraden** [comment]
I had this error too - passport uses the google plus API which isn't available for google apps for enterprise.

You can fix by monkey patching:

```
GoogleStrategy.prototype.userProfile = function(token, done) {
  done(null, {})
}
```

**Comment by pvtech** [comment]
Go to google developer console and enable the Google+ api

**Comment by khawajaumarfarooq** [comment]
Thanks pvtech, that was helpful!

**Comment by Victor08** [comment]
@pvtech , saved my life!

**Comment by MrFlick** [comment]
The URL of "https://www.googleapis.com/plus/v1/people/me/" seems to be hard coded in the Strategy.prototype.userProfile function. If you use a scope of "openid", then you can access the user info from "https://www.googleapis.com/plus/v1/people/me/openIdConnect" instead without having to go though the Google+ APIs.

**Comment by raselinfo** [comment]
Where i found Google+API

**Comment by UmarFKhawaja** [comment]
Google+ API has been retired by Google AFAIK.

**Comment by gauravtak** [comment]
> I had this error too - passport uses the google plus API which isn't available for google apps for enterprise.
> 
> You can fix by monkey patching:
> 
> ```
> GoogleStrategy.prototype.userProfile = function(token, done) {
>   done(null, {})
> }
> ```

this works, thank you 🙂😊
