### ISSUE TITLE
Dynamic callbackURL

### ISSUE THREAD

**Issue by lukezheng** [jaredhanson/passport-google-oauth#74]
Seems like passport-facebook supports dynamic callbackURL,

`passport.authenticate('facebook', { callbackURL: '/auth/example/callback?foo=bar' });`

Tried doing the same thing with v0.2.0 passport-google-oauth, but got 

```
TokenError: Missing parameter: redirect_uri
    at Strategy.OAuth2Strategy.parseErrorResponse (/Users/lukezheng/git/spoton/business/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/lib/strategy.js:298:12)
    at Strategy.OAuth2Strategy._createOAuthError (/Users/lukezheng/git/spoton/business/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/lib/strategy.js:345:16)
    at /Users/lukezheng/git/spoton/business/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/lib/strategy.js:171:43
    at /Users/lukezheng/git/spoton/business/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:177:18
    at passBackControl (/Users/lukezheng/git/spoton/business/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:124:9)
    at IncomingMessage.<anonymous> (/Users/lukezheng/git/spoton/business/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at /Users/lukezheng/git/spoton/business/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at process._tickDomainCallback [as _tickCallback] (node.js:463:13)
```

Is a dynamic callBackURL not supported in `passport.authenticate()`?

**Comment by bachvtuan** [comment]
The same situation here. I use google passport to authenticate Google Drive and Youtube. 
when I make custom callback for youtube, Passport always use default callback from Google Drive.

**Comment by jayachakladar** [comment]
I use google passport to create new users in the system, and also to link an existing local users to its google account. In each of these cases, my redirect needs to be different(new user comes into  dashboard and logged in user stays in the page from where the linking has been requested). Is there a way to achieve that, other than dynamic callbackurl ? Or is it again a dynamic callback url support that is required.

**Comment by natario1** [comment]
Any solution to this guys?

**Comment by bachvtuan** [comment]
@natario1 In my case, I use  same url  for authenticate via Google Drive and Youtube. After I get the token ( not sure it's from Google Drive or Youtube ) I need to request to https://www.googleapis.com/oauth2/v3/tokeninfo?access_token={returned_token} to get the scope. Then you can see it's youtube or google_drive.
Good luck !

**Comment by tomivm** [comment]
this work for me.
```
const configureGoogleStrategy = app => {
  let domain;
  app.get('/login/google', (req, res, next) => {
    domain = req.headers.referer;
    //if referer is private insert default hostname
    if (!domain) {
      domain = 'https://app.cboard.io/';
    }
    return passport.authenticate('google', {
      session: false,
      scope: config.google.SCOPE,
      callbackURL: domain + config.googleCallbackPath
    })(req, res, next);
  });

  // GET /login/google/callback
  //   Use passport.authenticate() as route middleware to authenticate the
  //   request.  If authentication fails, the user will be redirected back to the
  //   login page.  Otherwise, the primary route function function will be called,
  //   which, in this example, will redirect the user to the home page.
  app.get(
    '/login/google/callback',
    (req, res, next) => {
      return passport.authenticate('google', {
        callbackURL: domain + config.googleCallbackPath,
        failureRedirect: '/',
        session: false
      })(req, res, next);
    },
    (req, res) => {
      res.json(req.user);
    }
  );
};
```
