### ISSUE TITLE
InternalOAuthError: failed to fetch user profile

### ISSUE THREAD

**Issue by mastermind202** [jaredhanson/passport-google-oauth#77]
User seems to get authenticated but I get this error before the GoogleStrategy() callback function is executed.  Has anyone found a solution to this?

```
createCredentials() is deprecated, use tls.createSecureContext instead
InternalOAuthError: failed to fetch user profile
    at /home/sergei/projects/www/jobpact/jp-recruiter/node/node_modules/passport-google-oauth/lib/passport-google-oauth/oauth2.js:88:28
    at passBackControl (/home/sergei/projects/www/jobpact/jp-recruiter/node/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:124:9)
    at IncomingMessage.<anonymous> (/home/sergei/projects/www/jobpact/jp-recruiter/node/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

```

**Comment by mastermind202** [comment]
Disregard.  Looking at the source and logging the actual error led me to the issue:

```
message: "Access Not Configured. The API (Google+ API) is not enabled for your project. Please use the Google Developers Console to update your configuration."
```
