### ISSUE TITLE
TokenError:Code was already redeemed.

### ISSUE THREAD

**Issue by mateutek** [jaredhanson/passport-google-oauth#82]
TokenError: Code was already redeemed. at Strategy.OAuth2Strategy.parseErrorResponse (/Users/i312487/webbies/aidkit-fullstack/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/lib/strategy.js:298:12) at Strategy.OAuth2Strategy._createOAuthError (/Users/i312487/webbies/aidkit-fullstack/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/lib/strategy.js:345:16) at /Users/i312487/webbies/aidkit-fullstack/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/lib/strategy.js:171:43 at /Users/i312487/webbies/aidkit-fullstack/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:176:18 at passBackControl (/Users/i312487/webbies/aidkit-fullstack/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:123:9) at IncomingMessage.<anonymous> (/Users/i312487/webbies/aidkit-fullstack/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:142:7) at IncomingMessage.emit (events.js:129:20) at _stream_readable.js:908:16 at process._tickCallback (node.js:355:11)

Any ideas how to solve this ??

**Comment by tonyspiro** [comment]
+1

**Comment by amitsprofile** [comment]
+1

**Comment by aendrew** [comment]
Have suddenly run into this as well...

**Comment by oebspm** [comment]
+1

**Comment by aendrew** [comment]
Seems Google doesn't like it if you use the same tokens both for Dev and Prod. Fortunately, on the "credentials" page of the API Console, you can generate additional tokens and so have different config for both local dev and production.

**Comment by amitsprofile** [comment]
Just found that two request is coming to the server. That's why the problem
is. But why two request? Do you guys capture the port and check if same is
happening.

Thanks
Amit

**Comment by abaumer** [comment]
+1

**Comment by abaumer** [comment]
Tried creating alt creds in google api console for localhost, but still getting the same "TokenError:Code was already redeemed." as mateutek

**Comment by pbrain19** [comment]
+1

**Comment by pbrain19** [comment]
For me everything works fine if I delete the user. I try to log in a user with fb it works, then with google + throws the error. I delete the user and session and re do the opposite it works just fine... Guess passport is not handling this correctly.

**Comment by amitsprofile** [comment]
There seems to be something related with Android phones. Is anyone getting
the same error with browser or different phones?

On Sun, Jul 5, 2015 at 7:01 PM, Paul Garcia <notifications@github.com>
wrote:

> For me everything works fine if I delete the user. I try to log in a user
> with fb it works, then with google + throws the error. I delete the user
> and session and re do the opposite it works just fine... Guess passport is
> not handling this correctly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaredhanson/passport-google-oauth/issues/82#issuecomment-118691461>
> .
>



-- 
San Jose State University
Student, MS in Software Engineering
Email: amit.agrawal@sjsu.edu
Mobile: +1 408-598-7995

**Comment by oebspm** [comment]
I found out the way to reproduce the issue:
1) Logout from your google account
2) Open your site
3) Try to login using you gmail account and enter password.
This causes the error.

The workaround is:
1) Open your gmail account and login
2) Open your site and login using google account.
It works fine in this way.

**Comment by jereme-leandev** [comment]
+1

**Comment by AlexanderSuv** [comment]
+ 1 
Same issue, two requests coming: first with the user's profile, second with the error

**Comment by AlexanderSuv** [comment]
Worked for me

> Two callbacks, second with:  **TokenError:Code was already redeemed**
```javascript
router.get('/auth/google/callback',
	passport.authenticate('google', { failureRedirect: '#/signIn' }),
	function(req, res) {
// relative path
		res.redirect('#/home');
	});
```

> One callback. No error
```javascript
router.get('/auth/google/callback',
	passport.authenticate('google', { failureRedirect: '#/signIn' }),
	function(req, res) {
 // absolute path
		res.redirect('http://localhost:8888/#/home');
	});
```

I hope it will help someone.

**Comment by jeremejazz** [comment]
I got it working. My problem was that I didn't serialize it properly

**Comment by tonyspiro** [comment]
Thanks @AlexanderSuv Adding the full path fixed it for me!

**Comment by mrasband** [comment]
Tried various ways that worked for others with little success, instead I added a really simple middleware to check if a user is already authenticated and to just skip the call if they are, reason being there is little reason to leave a button around that would even let them hit that route a second time and to only cover the edge cases (such as hitting back).  For anyone interested:

```
.get('/google', function(req, res, next) {
    if (!req.user) { // Not already logged in, probably okay to try to hit the oauth provider
      return next();
    }
    res.redirect('/profile'); // Already logged in, send them where I want them after the callback anyway.
  }, passport.authenticate('google', {
    scope: ['email', 'profile']
  }))
```

**Comment by aliatsis** [comment]
@jaredhanson is there any hope for a solution to this bug?

**Comment by thoughtpalette** [comment]
:+1:

**Comment by divneet** [comment]
hey ,  i'm still facing a similar problem can anyone help me out here ?

**Comment by 1m4x** [comment]
That's an annoying bug.
Same for me, but using full path does not seem to help.

**Comment by san-php** [comment]
Is there any other solution for this..? i tried everything mentioned here and nothing solved the issue.

**Comment by skyserpent** [comment]
:+1:

I'm in the same boat just noticed this today

**Comment by lsaavedr** [comment]
@san-php  @maxevilmind and with ntpdate-debian? this fix the problem in my case...

**Comment by samjacoby** [comment]
Ran across this as well — the issue (for me), as in adding passport to my express middleware, like so:
```
app.use(passport.authenticate('google', { scope: ['profile'] } ));
```
I did not subsequently remove the call from the callback route, resulting in duplicate calls, first by the middleware intercepting the request, and then again, by the route callback chain. Not sure if this is what everyone's running into, but removing the second `passport.authenticate` request (and leaving it all to the middleware) solved it for me.

**Comment by alexspence** [comment]
After hours of mashing my keyboard I found a solution that works for me.  Something is wonky when you call /google/callback.. It appears to trigger /google again.  Some express expert can probably explain why.. Simply change the routes and it works.

```
app.get('/auth/google/get',
  passport.authenticate('google', { scope: 
    [ 'https://www.googleapis.com/auth/plus.login',
    , 'https://www.googleapis.com/auth/plus.profile.emails.read' ] }
));

app.get( '/auth/google/callback', 
    passport.authenticate( 'google', { 
        successRedirect: '/auth/google/success',
        failureRedirect: '/auth/google/failure'
}));
```

**Comment by pmadruga** [comment]
As @samjacoby mentioned, removing the second passport authenticate did the trick.

**Comment by shu5955** [comment]
I am running into the same problem. I have checked all my routes and used all the examples above. However, I did not find much help. Any suggestions?

**Comment by hristo-vrigazov** [comment]
Any updates on that one? I am experiencing the same problem.

**Comment by itaiif** [comment]
Same issue!! 

Any other suggestions?

**Comment by feorean** [comment]
In my case I was trying to set cookies at the callback that was giving that error. I assume, (as someone already mentioned above) it generates **another** request that raises this error.
I suggest looking into call back function and remove some stuff.



    app.get('/auth/google/callback', 
      passport.authenticate('google', { failureRedirect: '/login' }),
      function(req, res) {

       //***HERE this causes that error
                  //cookies.setCookie(res, 'NAME', 'VALUE');
       //
        
      	console.log("Login successfull");

        res.redirect('/');
      });

**Comment by toddcoulson** [comment]
I am having the same issue here. I don't want to add in mongoose or find a db afterward, I just want to trace back the data once recieved. Here is my code for my routes (I have also tried these with localhost:9000 too and it also doesn't work):
```
app.get('/auth/google', passport.authenticate('google', {scope: ['profile', 'email']}));

app.get('/auth/google/callback', 
	  passport.authenticate('google', { successRedirect: '/profile',
	                                      failureRedirect: '/' }));
```
Here is my strategy:
```
passport.use(new GoogleStrategy(
        {
            clientID: configAuth.googleAuth.clientID,
            clientSecret: configAuth.googleAuth.clientSecret,
            callbackURL: configAuth.googleAuth.callbackURL
        },
        function(accessToken, refreshToken, profile, done) {
            console.log(profile.id);
        }
    ));
```
I don't understand what has fixed this issue. I either get this already redeemed error or I get an invalid code error. Let me know if you see anything out of the norm.

**Comment by codchen** [comment]
This works for me:

I registered app.use('/google', passport.authenticate) before app.use('/google/callback'), resulting in 'google/callback' got called twice and the TokenError. 
So I simply have app.use('/google/callback') registered before app.use('/google'). However I do feel that it's best practice to use '/google/auth' instead of '/google' (a.k.a. avoid prefix endpoint when it being prefix doesn't make sense).

Hope that helps

**Comment by chris751** [comment]
i have tried everything on this thread. and still get TokenError: Code was already redeemed.

Does anyone have a solution that worked, that they're willing to share?

**Comment by AdityaAnand1** [comment]
I cannot believe what a headache integrating google plus is. 

Can someone please share a complete working solution? (If one exists)

**Comment by morsilla182** [comment]
Hello,

In my case, I don't think this a problem at all.... What happened for me (I use a Macbook with Safari) is that when I write the URL, the browser have in memory previous callback routes I have used before so it automatically fill the URL with the callback and send the request before I hit enter or change the URL for the correct one to login through google, hence this callback was used before with another authentication test I made so I get the Token already redeemed error, but once I modify the route and go to the login and try authenticate it passes without error.

So when doing your test, do not write the URL manually (or delete the history) to avoid the browser automatically fill out your request with a callback route.

For instance, my login route is something like: localhost:5000/auth

and my callback from google is something like: localhost:5000/auth/callback...........

so when I am typing the login route, the browser automatically fill with a previous callback route used before and send the request, getting this Token already redeemed error.

Hope this can help!

**Comment by prabhakarupadhyay** [comment]
I have literally been nagging my head on this issue for more than 5 days now. I have tried almost every solution on internet but nothing seems to be working. My problem is quite similar but weird at the same time.Google-Passport auth works just fine on local host and other cloud platform like openshift but fails to work on google cloud. I keep getting this error in my passport callback.

plzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz HELP!!!!!!

**Comment by prabhakarupadhyay** [comment]
and its me who has even weird kinda problem than just the one everyone is facing. My authentication works just fine on localhost and on many cloud platforms like openshift and nodejitsu but gives me the code redeem error when i try login from google cloud platform(GAE). I have tried everything on this page and on many other pages but none seems to work. I have started thinking its some googles internal fault when it comes to google Oauth2 with passport specially on their own platform. If someone is still facing the problem i'd suggest a shift to facebook authentication. RIP GOOGLE!!

**Comment by DrissiReda** [comment]
I tried all solutions on this thread and I'm still getting code already redeemed...

**Comment by luckyriver0** [comment]
I was experiencing the same problem. In my case, the request  for publishing access token was coming to server twice. First request was successful but second request caused this error. My implementation was wrong.

I recommend you to check if the request for the access token has been sent twice in your application process (not access log).

Thank you.

**Comment by harindersingh** [comment]
Handle the callbacks properly

app.post('/login',
  passport.authenticate('local', { successRedirect: '/',
                                   failureRedirect: '/login',
                                   failureFlash: true })
);

Using the above resolved same issue for me.

**Comment by debotos** [comment]
I was receiving (endless loading...) and then 'TokenError: Code was already redeemed'.
placing the callback route '/auth/google/callback' before auth route '/auth/google' worked for me.

**Comment by JulGotheKey** [comment]
Same problem and i have tried everything on this thread too ...

**Comment by dershao** [comment]
In my case it was my server wasn't actually connected to a database but I attempted to query the database in my GoogleStrategy callback function.

**Comment by Ajmaljalal** [comment]
This defenetly worked. beside that, if you change the order it will also work. ```/auth/google/callback``` is better to be before the ```/auth/google```

```
  app.use(
        '/auth/google/callback', 
        passport.authenticate('google'),
        (req, res) => {
            res.redirect('/dashboard');
        }
    );

app.use(
        '/auth/google',  
        passport.authenticate('google', {
            scope: ['profile', 'email']
        }) 
        
    );
    
```
